dist: trusty
before_install:
   - nvm install 0.10
install:
  # Disable Travis CI's built-in NVM installation
  - mv ~/.nvm ~/.travis-nvm-disabled
  - pip install coveralls
  - tools/travis/setup-$TEST_SUITE
  - tools/clean-venv-cache --travis
cache:
  - apt: false
  - directories:
    - $HOME/zulip-venv-cache
    - $HOME/zulip-npm-cache
    - $HOME/zulip-emoji-cache
    - $HOME/node
env:
  global:
    - COVERAGE_FILE=var/.coverage
    - COVERALLS_PARALLEL=true
    - COVERALLS_SERVICE_NAME=travis-pro
    - COVERALLS_REPO_TOKEN=hnXUEBKsORKHc8xIENGs9JjktlTb2HKlG
    - BOTO_CONFIG=/tmp/nowhere
language: python
matrix:
  include:
    - python: "3.4"
      env: TEST_SUITE=static-analysis
    - python: "3.4"
      env: TEST_SUITE=production
    - python: "2.7"
      env: TEST_SUITE=production
    - python: "2.7"
      env: TEST_SUITE=frontend
    - python: "3.4"
      env: TEST_SUITE=frontend
    - python: "2.7"
      env: TEST_SUITE=backend
    - python: "3.4"
      env: TEST_SUITE=backend
# command to run tests
script:
  - unset GEM_PATH
  - ./tools/travis/$TEST_SUITE
sudo: required
services:
- docker
addons:
  artifacts:
    paths:
      - $(ls var/casper/* | tr "\n" ":")
      - $(ls /tmp/zulip-test-event-log/* | tr "\n" ":")
  postgresql: "9.3"
after_success:
  coveralls
notifications:
  webhooks:
    urls:
      - https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN
      - https://zulip.org/zulipbot/travis
    on_success: always
    on_failure: always
